CREATE DATABASE TRATAMIENTOS;
USE TRATAMIENTOS;

CREATE TABLE USUARIO (
    ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50),
    SEXO CHAR(1),
    FECHA_NACIMIENTO DATE,
    TIPO_SANGRE ENUM(
        'A+', 
        'A-', 
        'B+', 
        'B-', 
        'AB+', 
        'AB-', 
        'O+', 
        'O-'),
    DONADOR_ORGANOS BOOLEAN,
    ALERGIAS TEXT,
    PADECIMIENTOS TEXT,
    ROL ENUM('ADMIN', 'USUARIO')
);

CREATE TABLE TRATAMIENTO (
    ID_TRATAMIENTO INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT,
    NOMBRE_TRATAMIENTO VARCHAR(50),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    ESTADO ENUM(
        'Activo', 
        'Suspendido', 
        'Finalizado'),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE MEDICAMENTO (
    ID_MEDICAMENTO INT PRIMARY KEY AUTO_INCREMENT,
    ID_TRATAMIENTO INT,
    NOMBRE VARCHAR(50),
    DOSIS VARCHAR(50),
    HORA TIME,
    OBSERVACION TEXT,
    INTERVALO INT,
    FOREIGN KEY (ID_TRATAMIENTO) REFERENCES TRATAMIENTO(ID_TRATAMIENTO)
);

CREATE TABLE HISTORIAL (
    ID_HISTORIAL INT PRIMARY KEY AUTO_INCREMENT,
    FECHA_HORA DATETIME,
    ESTADO ENUM(
        'Tomado', 
        'Omitido', 
        'Pospuesto', 
        'Cancelado'),
    OBSERVACION TEXT,
    ID_MEDICAMENTO INT,
    FOREIGN KEY (ID_MEDICAMENTO) REFERENCES MEDICAMENTO(ID_MEDICAMENTO)
);

CREATE TABLE ALARMA (
    ID_ALARMA INT PRIMARY KEY AUTO_INCREMENT,
    ID_MEDICAMENTO INT,
    HORA_PROGRAMADA DATETIME,
    ESTADO ENUM(
        'ENVIADA', 
        'PENDIENTE', 
        'CUMPLIDA', 
        'CANCELADA'),
    INTERVALO_POSPOSICION INT,
    FOREIGN KEY (ID_MEDICAMENTO) REFERENCES MEDICAMENTO(ID_MEDICAMENTO)
);
